/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApplicantsRouteImport } from './routes/applicants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicantsIdRouteImport } from './routes/applicants_.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantsRoute = ApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantsIdRoute = ApplicantsIdRouteImport.update({
  id: '/applicants_/$id',
  path: '/applicants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicants': typeof ApplicantsRoute
  '/applications': typeof ApplicationsRoute
  '/decisions': typeof DecisionsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/applicants/$id': typeof ApplicantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicants': typeof ApplicantsRoute
  '/applications': typeof ApplicationsRoute
  '/decisions': typeof DecisionsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/applicants/$id': typeof ApplicantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicants': typeof ApplicantsRoute
  '/applications': typeof ApplicationsRoute
  '/decisions': typeof DecisionsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/applicants_/$id': typeof ApplicantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applicants'
    | '/applications'
    | '/decisions'
    | '/messages'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/applicants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applicants'
    | '/applications'
    | '/decisions'
    | '/messages'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/applicants/$id'
  id:
    | '__root__'
    | '/'
    | '/applicants'
    | '/applications'
    | '/decisions'
    | '/messages'
    | '/reports'
    | '/scholarships'
    | '/settings'
    | '/applicants_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicantsRoute: typeof ApplicantsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DecisionsRoute: typeof DecisionsRoute
  MessagesRoute: typeof MessagesRoute
  ReportsRoute: typeof ReportsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SettingsRoute: typeof SettingsRoute
  ApplicantsIdRoute: typeof ApplicantsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicants': {
      id: '/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof ApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicants_/$id': {
      id: '/applicants_/$id'
      path: '/applicants/$id'
      fullPath: '/applicants/$id'
      preLoaderRoute: typeof ApplicantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicantsRoute: ApplicantsRoute,
  ApplicationsRoute: ApplicationsRoute,
  DecisionsRoute: DecisionsRoute,
  MessagesRoute: MessagesRoute,
  ReportsRoute: ReportsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SettingsRoute: SettingsRoute,
  ApplicantsIdRoute: ApplicantsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
