/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScholarshipsRouteImport } from './routes/dashboard.scholarships'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardExploreRouteImport } from './routes/dashboard.explore'
import { Route as DashboardEssaysRouteImport } from './routes/dashboard.essays'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardUniversityUniversityIdRouteImport } from './routes/dashboard.university.$universityId'
import { Route as DashboardApplicationsApplicationIdRouteImport } from './routes/dashboard.applications_.$applicationId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScholarshipsRoute = DashboardScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExploreRoute = DashboardExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEssaysRoute = DashboardEssaysRouteImport.update({
  id: '/essays',
  path: '/essays',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUniversityUniversityIdRoute =
  DashboardUniversityUniversityIdRouteImport.update({
    id: '/university/$universityId',
    path: '/university/$universityId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardApplicationsApplicationIdRoute =
  DashboardApplicationsApplicationIdRouteImport.update({
    id: '/applications_/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/applications/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/university/$universityId': typeof DashboardUniversityUniversityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/applications/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/university/$universityId': typeof DashboardUniversityUniversityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/essays': typeof DashboardEssaysRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scholarships': typeof DashboardScholarshipsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/applications_/$applicationId': typeof DashboardApplicationsApplicationIdRoute
  '/dashboard/university/$universityId': typeof DashboardUniversityUniversityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/essays'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard/verification'
    | '/dashboard/'
    | '/dashboard/applications/$applicationId'
    | '/dashboard/university/$universityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/essays'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard/verification'
    | '/dashboard'
    | '/dashboard/applications/$applicationId'
    | '/dashboard/university/$universityId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/essays'
    | '/dashboard/explore'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/scholarships'
    | '/dashboard/settings'
    | '/dashboard/verification'
    | '/dashboard/'
    | '/dashboard/applications_/$applicationId'
    | '/dashboard/university/$universityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scholarships': {
      id: '/dashboard/scholarships'
      path: '/scholarships'
      fullPath: '/dashboard/scholarships'
      preLoaderRoute: typeof DashboardScholarshipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/explore': {
      id: '/dashboard/explore'
      path: '/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/essays': {
      id: '/dashboard/essays'
      path: '/essays'
      fullPath: '/dashboard/essays'
      preLoaderRoute: typeof DashboardEssaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/university/$universityId': {
      id: '/dashboard/university/$universityId'
      path: '/university/$universityId'
      fullPath: '/dashboard/university/$universityId'
      preLoaderRoute: typeof DashboardUniversityUniversityIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications_/$applicationId': {
      id: '/dashboard/applications_/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/dashboard/applications/$applicationId'
      preLoaderRoute: typeof DashboardApplicationsApplicationIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardEssaysRoute: typeof DashboardEssaysRoute
  DashboardExploreRoute: typeof DashboardExploreRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardScholarshipsRoute: typeof DashboardScholarshipsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardApplicationsApplicationIdRoute: typeof DashboardApplicationsApplicationIdRoute
  DashboardUniversityUniversityIdRoute: typeof DashboardUniversityUniversityIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardEssaysRoute: DashboardEssaysRoute,
  DashboardExploreRoute: DashboardExploreRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardScholarshipsRoute: DashboardScholarshipsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardApplicationsApplicationIdRoute:
    DashboardApplicationsApplicationIdRoute,
  DashboardUniversityUniversityIdRoute: DashboardUniversityUniversityIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
