import type {
  University, Application, StudentDocument, Scholarship,
  Notification, StudentProfile, BankPartner, FinancialSummary,
} from "./types";

export const universities: University[] = [
  {
    id: "uni-1",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    logo: "🏛️",
    banner: "",
    description: "A globally recognized institution offering world-class programs across sciences, engineering, and the humanities. Known for cutting-edge research and a diverse student body.",
    programs: ["Computer Science", "Engineering", "Business Administration", "Medicine", "Data Science"],
    tuitionMin: 35000,
    tuitionMax: 55000,
    currency: "USD",
    applicationDeadline: "2026-01-15",
    verificationPreference: "preferred",
    scholarshipAvailable: true,
    scholarshipNote: "Merit-based scholarships up to $10,000/year for international students",
    admissionsNotes: "Strong academic record required. Pre-verified students receive priority review.",
    ranking: "#18 World",
    acceptanceRate: "43%",
    website: "https://utoronto.ca",
  },
  {
    id: "uni-2",
    name: "University of Edinburgh",
    country: "United Kingdom",
    city: "Edinburgh",
    logo: "🎓",
    banner: "",
    description: "One of the oldest and most prestigious universities in the English-speaking world, offering exceptional programs in arts, sciences, and medicine.",
    programs: ["International Relations", "Computer Science", "Medicine", "Law", "Philosophy"],
    tuitionMin: 25000,
    tuitionMax: 42000,
    currency: "USD",
    applicationDeadline: "2026-01-31",
    verificationPreference: "required",
    scholarshipAvailable: true,
    scholarshipNote: "Global Scholarship Programme for outstanding international applicants",
    admissionsNotes: "Financial verification required before application review begins.",
    ranking: "#22 World",
    acceptanceRate: "40%",
    website: "https://ed.ac.uk",
  },
  {
    id: "uni-3",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    logo: "🔬",
    banner: "",
    description: "Germany's top technical university with strong ties to industry. Known for engineering, natural sciences, and innovation-focused programs.",
    programs: ["Mechanical Engineering", "Informatics", "Physics", "Architecture", "Electrical Engineering"],
    tuitionMin: 5000,
    tuitionMax: 12000,
    currency: "USD",
    applicationDeadline: "2026-03-15",
    verificationPreference: "optional",
    scholarshipAvailable: true,
    scholarshipNote: "DAAD scholarships available; low tuition makes verification simpler",
    admissionsNotes: "Proof of funds for living expenses may be required for visa processing.",
    ranking: "#30 World",
    acceptanceRate: "8%",
    website: "https://tum.de",
  },
  {
    id: "uni-4",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    logo: "🦘",
    banner: "",
    description: "Australia's leading university with a strong emphasis on research impact and graduate employability. Offers diverse programs for international students.",
    programs: ["Biomedicine", "Commerce", "Engineering", "Arts", "Environmental Science"],
    tuitionMin: 30000,
    tuitionMax: 48000,
    currency: "USD",
    applicationDeadline: "2026-05-31",
    verificationPreference: "preferred",
    scholarshipAvailable: true,
    scholarshipNote: "Melbourne International Scholarship covers up to 50% of tuition",
    admissionsNotes: "Conditional offers available for students awaiting financial pre-verification.",
    ranking: "#14 World",
    acceptanceRate: "70%",
    website: "https://unimelb.edu.au",
  },
  {
    id: "uni-5",
    name: "McGill University",
    country: "Canada",
    city: "Montreal",
    logo: "🍁",
    banner: "",
    description: "One of Canada's most prestigious universities, known for medical research, strong liberal arts programs, and a vibrant multicultural campus.",
    programs: ["Medicine", "Political Science", "Computer Engineering", "Music", "Neuroscience"],
    tuitionMin: 20000,
    tuitionMax: 45000,
    currency: "USD",
    applicationDeadline: "2026-01-15",
    verificationPreference: "preferred",
    scholarshipAvailable: true,
    scholarshipNote: "Entrance scholarships up to $12,000 for qualified international students",
    admissionsNotes: "Applications reviewed holistically. Pre-verification strengthens your profile.",
    ranking: "#31 World",
    acceptanceRate: "46%",
    website: "https://mcgill.ca",
  },
  {
    id: "uni-6",
    name: "University College London",
    country: "United Kingdom",
    city: "London",
    logo: "🇬🇧",
    banner: "",
    description: "A leading multidisciplinary university in the heart of London, consistently ranked among the world's top institutions for research and teaching.",
    programs: ["Architecture", "Economics", "Neuroscience", "Law", "Global Health"],
    tuitionMin: 28000,
    tuitionMax: 50000,
    currency: "USD",
    applicationDeadline: "2026-01-25",
    verificationPreference: "required",
    scholarshipAvailable: false,
    scholarshipNote: "Limited scholarship availability for 2026 intake",
    admissionsNotes: "Full financial verification must be completed before unconditional offers.",
    ranking: "#9 World",
    acceptanceRate: "35%",
    website: "https://ucl.ac.uk",
  },
  {
    id: "uni-7",
    name: "ETH Zurich",
    country: "Switzerland",
    city: "Zurich",
    logo: "🇨🇭",
    banner: "",
    description: "A world-leading science and technology university known for research excellence and producing Nobel laureates.",
    programs: ["Computer Science", "Physics", "Mathematics", "Civil Engineering", "Biology"],
    tuitionMin: 8000,
    tuitionMax: 15000,
    currency: "USD",
    applicationDeadline: "2026-12-15",
    verificationPreference: "optional",
    scholarshipAvailable: true,
    scholarshipNote: "Excellence Scholarship covers living costs and tuition",
    admissionsNotes: "Highly competitive. Academic merit is the primary selection criterion.",
    ranking: "#7 World",
    acceptanceRate: "27%",
    website: "https://ethz.ch",
  },
  {
    id: "uni-8",
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver",
    logo: "🌲",
    banner: "",
    description: "A top public research university set against one of the most beautiful campuses in the world. Known for sustainability research and community engagement.",
    programs: ["Forestry", "Computer Science", "Business", "Kinesiology", "Film Production"],
    tuitionMin: 30000,
    tuitionMax: 50000,
    currency: "USD",
    applicationDeadline: "2026-01-15",
    verificationPreference: "preferred",
    scholarshipAvailable: true,
    scholarshipNote: "International Major Entrance Scholarship (IMES) up to full tuition",
    admissionsNotes: "Pre-verified students may receive faster admissions decisions.",
    ranking: "#34 World",
    acceptanceRate: "52%",
    website: "https://ubc.ca",
  },
];

export const applications: Application[] = [
  {
    id: "app-1",
    universityId: "uni-1",
    universityName: "University of Toronto",
    program: "Computer Science",
    status: "under_review",
    verificationStatus: "pre_verified",
    scholarshipStatus: "applied",
    submittedDate: "2025-11-20",
    lastUpdated: "2026-04-10",
    estimatedScholarship: 8000,
    tuitionAmount: 45000,
    notes: ["Application received and under review.", "Pre-verification status confirmed."],
    timeline: [
      { id: "t1", title: "Application Started", description: "You began your application", date: "2025-11-01", completed: true },
      { id: "t2", title: "Documents Uploaded", description: "All required documents submitted", date: "2025-11-15", completed: true },
      { id: "t3", title: "Application Submitted", description: "Application sent for review", date: "2025-11-20", completed: true },
      { id: "t4", title: "Under Review", description: "Admissions team reviewing your application", date: "2026-04-10", completed: false, current: true },
      { id: "t5", title: "Decision", description: "Final admission decision", date: "", completed: false },
    ],
  },
  {
    id: "app-2",
    universityId: "uni-2",
    universityName: "University of Edinburgh",
    program: "International Relations",
    status: "awaiting_verification",
    verificationStatus: "under_review",
    scholarshipStatus: "not_applied",
    submittedDate: "2025-12-01",
    lastUpdated: "2026-04-08",
    estimatedScholarship: 0,
    tuitionAmount: 32000,
    notes: ["Application on hold until financial verification is complete.", "Consider applying for the Global Scholarship."],
    timeline: [
      { id: "t1", title: "Application Started", description: "You began your application", date: "2025-11-25", completed: true },
      { id: "t2", title: "Application Submitted", description: "Application sent for review", date: "2025-12-01", completed: true },
      { id: "t3", title: "Awaiting Verification", description: "Financial verification needed", date: "2026-01-15", completed: false, current: true },
      { id: "t4", title: "Review", description: "Admissions review", date: "", completed: false },
      { id: "t5", title: "Decision", description: "Final admission decision", date: "", completed: false },
    ],
  },
  {
    id: "app-3",
    universityId: "uni-4",
    universityName: "University of Melbourne",
    program: "Commerce",
    status: "conditionally_accepted",
    verificationStatus: "pending_submission",
    scholarshipStatus: "awarded",
    submittedDate: "2025-10-15",
    lastUpdated: "2026-03-28",
    estimatedScholarship: 15000,
    tuitionAmount: 38000,
    notes: ["Conditional acceptance issued!", "Complete financial verification to receive full offer.", "Melbourne International Scholarship awarded."],
    timeline: [
      { id: "t1", title: "Application Started", description: "You began your application", date: "2025-10-01", completed: true },
      { id: "t2", title: "Application Submitted", description: "Application sent for review", date: "2025-10-15", completed: true },
      { id: "t3", title: "Conditional Acceptance", description: "You received a conditional offer", date: "2026-03-28", completed: true, current: true },
      { id: "t4", title: "Financial Verification", description: "Complete verification to finalize", date: "", completed: false },
      { id: "t5", title: "Final Enrollment", description: "Confirm your enrollment", date: "", completed: false },
    ],
  },
  {
    id: "app-4",
    universityId: "uni-3",
    universityName: "Technical University of Munich",
    program: "Informatics",
    status: "draft",
    verificationStatus: "not_started",
    scholarshipStatus: "not_applied",
    submittedDate: null,
    lastUpdated: "2026-04-12",
    estimatedScholarship: 0,
    tuitionAmount: 8000,
    notes: [],
    timeline: [
      { id: "t1", title: "Application Started", description: "Draft in progress", date: "2026-04-12", completed: false, current: true },
      { id: "t2", title: "Documents Upload", description: "Upload required documents", date: "", completed: false },
      { id: "t3", title: "Submit Application", description: "Send for review", date: "", completed: false },
    ],
  },
  {
    id: "app-5",
    universityId: "uni-6",
    universityName: "University College London",
    program: "Economics",
    status: "rejected",
    verificationStatus: "verified",
    scholarshipStatus: "not_applied",
    submittedDate: "2025-09-20",
    lastUpdated: "2026-02-15",
    estimatedScholarship: 0,
    tuitionAmount: 35000,
    notes: ["We regret to inform you that your application was not successful this cycle."],
    timeline: [
      { id: "t1", title: "Application Submitted", description: "Application sent", date: "2025-09-20", completed: true },
      { id: "t2", title: "Under Review", description: "Application reviewed", date: "2025-12-01", completed: true },
      { id: "t3", title: "Decision", description: "Application not accepted", date: "2026-02-15", completed: true },
    ],
  },
];

export const documents: StudentDocument[] = [
  { id: "doc-1", name: "Passport", category: "passport_id", status: "approved", uploadedDate: "2025-10-01", fileSize: "2.4 MB", notes: "Valid until 2030" },
  { id: "doc-2", name: "National ID Card", category: "passport_id", status: "approved", uploadedDate: "2025-10-01", fileSize: "1.1 MB", notes: "" },
  { id: "doc-3", name: "High School Transcript", category: "academic_records", status: "approved", uploadedDate: "2025-10-05", fileSize: "3.2 MB", notes: "Official certified copy" },
  { id: "doc-4", name: "University Transcript", category: "academic_records", status: "under_review", uploadedDate: "2025-11-10", fileSize: "2.8 MB", notes: "Awaiting verification from institution" },
  { id: "doc-5", name: "IELTS Score Report", category: "academic_records", status: "approved", uploadedDate: "2025-10-08", fileSize: "1.5 MB", notes: "Overall band score: 7.5" },
  { id: "doc-6", name: "Bank Statement (6 months)", category: "bank_statements", status: "uploaded", uploadedDate: "2026-03-15", fileSize: "4.1 MB", notes: "From Commercial Bank of Ethiopia" },
  { id: "doc-7", name: "Bank Verification Letter", category: "bank_statements", status: "missing", uploadedDate: null, fileSize: null, notes: "Request from your bank" },
  { id: "doc-8", name: "Sponsor Declaration Letter", category: "sponsor_letters", status: "uploaded", uploadedDate: "2026-02-20", fileSize: "1.8 MB", notes: "From parent/guardian" },
  { id: "doc-9", name: "Sponsor Bank Statement", category: "sponsor_letters", status: "needs_replacement", uploadedDate: "2026-01-10", fileSize: "3.5 MB", notes: "Statement must be within last 3 months" },
  { id: "doc-10", name: "Melbourne Scholarship Letter", category: "scholarship_letters", status: "approved", uploadedDate: "2026-03-30", fileSize: "0.8 MB", notes: "Melbourne International Scholarship confirmation" },
  { id: "doc-11", name: "Motivation Letter", category: "other", status: "uploaded", uploadedDate: "2025-11-01", fileSize: "0.5 MB", notes: "" },
  { id: "doc-12", name: "CV / Resume", category: "other", status: "approved", uploadedDate: "2025-11-01", fileSize: "0.6 MB", notes: "" },
];

export const scholarships: Scholarship[] = [
  {
    id: "sch-1",
    name: "Melbourne International Scholarship",
    provider: "University of Melbourne",
    amount: 15000,
    currency: "USD",
    eligibility: "International students with outstanding academic records. Minimum GPA 3.5.",
    deadline: "2026-04-30",
    status: "awarded",
    description: "Covers up to 50% of tuition fees for the duration of the program. Renewable annually based on academic performance.",
    coverageType: "Partial Tuition",
  },
  {
    id: "sch-2",
    name: "University of Toronto Lester B. Pearson Scholarship",
    provider: "University of Toronto",
    amount: 10000,
    currency: "USD",
    eligibility: "Nominated international students demonstrating exceptional academic achievement and creativity.",
    deadline: "2026-01-15",
    status: "applied",
    description: "Merit-based award for international students. Covers partial tuition and incidental fees.",
    coverageType: "Partial Tuition",
  },
  {
    id: "sch-3",
    name: "DAAD Study Scholarship",
    provider: "German Academic Exchange Service",
    amount: 12000,
    currency: "USD",
    eligibility: "Graduates with at least 6 semesters of academic study. Excellent academic record required.",
    deadline: "2026-10-15",
    status: "not_applied",
    description: "Funding for international students pursuing a Master's degree at German universities. Covers living expenses.",
    coverageType: "Living Expenses",
  },
  {
    id: "sch-4",
    name: "Mastercard Foundation Scholars Program",
    provider: "Mastercard Foundation",
    amount: 45000,
    currency: "USD",
    eligibility: "Academically talented students from Sub-Saharan Africa who face financial barriers to education.",
    deadline: "2026-02-28",
    status: "not_applied",
    description: "Comprehensive scholarship covering tuition, accommodation, travel, and living expenses for the full program duration.",
    coverageType: "Full Scholarship",
  },
  {
    id: "sch-5",
    name: "Chevening Scholarship",
    provider: "UK Government",
    amount: 30000,
    currency: "USD",
    eligibility: "Individuals with demonstrable leadership potential and strong academic background. Work experience required.",
    deadline: "2026-11-01",
    status: "not_applied",
    description: "Fully funded scholarship for one-year Master's programs in the UK. Covers tuition, living costs, and travel.",
    coverageType: "Full Scholarship",
  },
];

export const notifications: Notification[] = [
  { id: "n-1", title: "Application Update", message: "Your application to University of Toronto is now under review. The admissions team will evaluate your submission within 6-8 weeks.", category: "application_update", date: "2026-04-10", read: false, source: "University of Toronto" },
  { id: "n-2", title: "Conditional Acceptance", message: "Congratulations! You have received a conditional acceptance from University of Melbourne. Please complete your financial verification to receive a full offer.", category: "application_update", date: "2026-03-28", read: true, source: "University of Melbourne" },
  { id: "n-3", title: "Verification Document Required", message: "Your bank verification letter is missing. Please upload this document to proceed with your financial verification.", category: "missing_document", date: "2026-04-05", read: false, source: "Verifly" },
  { id: "n-4", title: "Sponsor Statement Update Needed", message: "Your sponsor's bank statement is older than 3 months. Please upload a recent statement to continue the verification process.", category: "verification_request", date: "2026-04-02", read: false, source: "Verifly" },
  { id: "n-5", title: "Scholarship Awarded!", message: "You have been awarded the Melbourne International Scholarship worth $15,000 per year. This has been applied to your funding breakdown.", category: "scholarship_update", date: "2026-03-30", read: true, source: "University of Melbourne" },
  { id: "n-6", title: "Edinburgh Verification Reminder", message: "University of Edinburgh requires financial verification to proceed with your application. Start the verification process now.", category: "verification_request", date: "2026-04-08", read: false, source: "University of Edinburgh" },
  { id: "n-7", title: "Application Rejected", message: "Unfortunately, your application to University College London for Economics was not successful this cycle.", category: "application_update", date: "2026-02-15", read: true, source: "University College London" },
  { id: "n-8", title: "New Scholarship Opportunity", message: "The Mastercard Foundation Scholars Program is now accepting applications. Check your eligibility and apply before the deadline.", category: "scholarship_update", date: "2026-04-01", read: false, source: "Verifly" },
  { id: "n-9", title: "Bank Review in Progress", message: "Commercial Bank of Ethiopia is currently reviewing your submitted financial documents. Estimated processing time: 5-7 business days.", category: "verification_request", date: "2026-03-20", read: true, source: "Commercial Bank of Ethiopia" },
  { id: "n-10", title: "Profile Reminder", message: "Complete your student profile to improve your application readiness score. You're 78% complete.", category: "general", date: "2026-03-15", read: true, source: "Verifly" },
  { id: "n-11", title: "Deadline Approaching", message: "The application deadline for University of Toronto and McGill University is January 15, 2026. Make sure your applications are submitted.", category: "application_update", date: "2025-12-20", read: true, source: "Verifly" },
  { id: "n-12", title: "Welcome to Verifly!", message: "Welcome aboard! Start by completing your profile, exploring universities, and understanding the financial verification process.", category: "general", date: "2025-09-01", read: true, source: "Verifly" },
];

export const studentProfile: StudentProfile = {
  id: "student-1",
  firstName: "Abebe",
  lastName: "Tadesse",
  email: "abebe.tadesse@example.com",
  phone: "+251-911-234-567",
  dateOfBirth: "2002-05-15",
  countryOfOrigin: "Ethiopia",
  nationality: "Ethiopian",
  passportNumber: "EP•••••89",
  currentAddress: "Addis Ababa, Ethiopia",
  intendedDegreeLevel: "Bachelor's",
  fieldOfStudy: "Computer Science",
  previousInstitution: "Addis Ababa Science & Technology University",
  gpa: "3.8 / 4.0",
  englishProficiency: "IELTS",
  testScore: "7.5",
  sponsorName: "Tadesse Bekele",
  sponsorRelationship: "Father",
  sponsorOccupation: "Business Owner",
  estimatedBudget: 50000,
  currency: "USD",
  savedUniversities: ["uni-1", "uni-3", "uni-5", "uni-7"],
  profileCompleteness: 78,
  middleName: "",
  preferredName: "Abel",
  gender: "Male",
  countryOfResidence: "Ethiopia",
  emergencyContactName: "Tadesse Bekele",
  emergencyContactPhone: "+251-911-998-877",
  graduationYear: "2024",
  gradingScale: "4.0 scale",
  academicInterests: "Machine learning, distributed systems, fintech",
  curriculum: "Ethiopian National Curriculum",
  stream: "Natural Science",
  schoolCountry: "Ethiopia",
  sponsorEmployer: "Bekele Trading PLC",
  householdSize: "5",
  dependents: "3",
  annualIncomeRange: "$25,000 – $50,000",
  fundingSource: "Family sponsorship + scholarship",
  liquidFunds: 18000,
  sponsorContribution: 22000,
  scholarshipExpectation: 10000,
  preApprovalStatus: "pending",
  preferredCountries: ["Canada", "Germany", "United Kingdom"],
  preferredIntake: "Fall 2026",
  preferredDegreeLevel: "Bachelor's",
  areasOfInterest: ["Computer Science", "Data Science", "Engineering"],
  notificationPreferences: "Email + In-app",
  lastUpdated: "2026-04-12",
  activities: [
    { id: "a1", name: "Robotics Club", role: "President", years: "2022–2024" },
    { id: "a2", name: "Math Olympiad Team", role: "Member", years: "2021–2024" },
    { id: "a3", name: "Community Code Mentor", role: "Volunteer Mentor", years: "2023–2024" },
  ],
  honors: [
    { id: "h1", name: "National Math Olympiad — Silver Medal", year: "2023" },
    { id: "h2", name: "School Valedictorian", year: "2024" },
    { id: "h3", name: "Regional Science Fair — 1st Place", year: "2022" },
  ],
};

export const bankPartners: BankPartner[] = [
  {
    id: "bank-1",
    name: "Commercial Bank of Ethiopia",
    country: "Ethiopia",
    logo: "🏦",
    description: "Ethiopia's largest commercial bank with dedicated international student verification services.",
    processingTime: "5-7 business days",
    requiredDocuments: ["Bank statement (6 months)", "Account verification letter", "Sponsor declaration"],
  },
  {
    id: "bank-2",
    name: "Dashen Bank",
    country: "Ethiopia",
    logo: "🏛️",
    description: "Leading private bank in Ethiopia offering streamlined financial verification for students.",
    processingTime: "3-5 business days",
    requiredDocuments: ["Bank statement (6 months)", "Fixed deposit certificate", "Income verification"],
  },
  {
    id: "bank-3",
    name: "Awash Bank",
    country: "Ethiopia",
    logo: "💰",
    description: "Pioneer private bank in Ethiopia providing quick verification and support for international students.",
    processingTime: "4-6 business days",
    requiredDocuments: ["Bank statement (3 months)", "Account balance certificate", "Reference letter"],
  },
];

export const financialSummary: FinancialSummary = {
  totalTuitionNeeded: 45000,
  estimatedScholarships: 23000,
  remainingAmount: 22000,
  verifiedAmount: 35000,
  currency: "USD",
  verificationStatus: "under_review",
};

export const verificationStatusLabels: Record<string, { label: string; description: string; color: string }> = {
  not_started: { label: "Not Started", description: "You haven't begun the financial verification process yet.", color: "muted" },
  pending_submission: { label: "Pending Submission", description: "You've started the process but haven't submitted all required documents.", color: "warning" },
  under_review: { label: "Under Bank Review", description: "Your documents are being reviewed by a partner bank. This typically takes 5-7 business days.", color: "info" },
  more_info_needed: { label: "More Information Needed", description: "The bank needs additional documents or clarification to proceed.", color: "warning" },
  pre_verified: { label: "Pre-Verified", description: "Your financial status has been preliminarily verified. This strengthens your application profile.", color: "success" },
  verified: { label: "Verified", description: "Your financial verification is complete and confirmed.", color: "success" },
  rejected: { label: "Rejected", description: "Your verification was not successful. You can review the reason and resubmit.", color: "destructive" },
};

export const applicationStatusLabels: Record<string, { label: string; color: string }> = {
  draft: { label: "Draft", color: "muted" },
  submitted: { label: "Submitted", color: "info" },
  under_review: { label: "Under Review", color: "info" },
  awaiting_verification: { label: "Awaiting Verification", color: "warning" },
  conditionally_accepted: { label: "Conditionally Accepted", color: "success" },
  accepted: { label: "Accepted", color: "success" },
  rejected: { label: "Rejected", color: "destructive" },
};

export const documentStatusLabels: Record<string, { label: string; color: string }> = {
  missing: { label: "Missing", color: "destructive" },
  uploaded: { label: "Uploaded", color: "info" },
  under_review: { label: "Under Review", color: "warning" },
  needs_replacement: { label: "Needs Replacement", color: "warning" },
  approved: { label: "Approved", color: "success" },
};

export const documentCategoryLabels: Record<string, string> = {
  passport_id: "Passport / ID",
  academic_records: "Academic Records",
  bank_statements: "Bank Statements",
  sponsor_letters: "Sponsor Letters",
  scholarship_letters: "Scholarship Letters",
  other: "Other Documents",
};

export type EssayStatus = "uploaded" | "missing";

export interface CoreEssay {
  id: string;
  name: string;
  description: string;
  status: EssayStatus;
  fileName?: string;
  uploadedDate?: string;
  wordCount?: number;
}

export interface SupplementalEssayPrompt {
  id: string;
  prompt: string;
  wordLimit: number;
  required: boolean;
}

export const coreEssays: CoreEssay[] = [
  {
    id: "essay-personal",
    name: "Personal Statement",
    description: "Your main essay shared across most applications. Tell your story, motivations, and aspirations.",
    status: "uploaded",
    fileName: "personal_statement_v3.pdf",
    uploadedDate: "2026-02-10",
    wordCount: 642,
  },
  {
    id: "essay-general",
    name: "General Essay",
    description: "A flexible essay used by universities that request a broad statement of background or interests.",
    status: "uploaded",
    fileName: "general_essay.pdf",
    uploadedDate: "2026-02-12",
    wordCount: 510,
  },
  {
    id: "essay-optional",
    name: "Optional Additional Information",
    description: "Optional context — special circumstances, gaps, or anything admissions teams should know.",
    status: "missing",
  },
];

// University-specific supplemental prompts surfaced during the apply flow.
export const universitySupplementalEssays: Record<string, SupplementalEssayPrompt[]> = {
  "uni-1": [
    { id: "uni-1-supp-1", prompt: "Why University of Toronto, and how does our program align with your goals?", wordLimit: 400, required: true },
  ],
  "uni-2": [
    { id: "uni-2-supp-1", prompt: "Describe a global issue you care about and how you would address it.", wordLimit: 500, required: true },
    { id: "uni-2-supp-2", prompt: "What community have you contributed to, and how?", wordLimit: 300, required: false },
  ],
  "uni-3": [
    { id: "uni-3-supp-1", prompt: "Tell us about an intellectual experience that shaped you.", wordLimit: 350, required: true },
  ],
};

